// Noms des modules de signal du bot, dans l'ordre du genome (evolution/genome.py, MODULES) : les 8 d'origine, puis
// les regles du moteur, portees dans evolution/modules/regles/.

export const NOMS_MODULES = {
  premiere_bougie: 'Première bougie',
  croisement: 'Croisement de moyennes',
  rsi: 'RSI',
  cassure: 'Cassure',
  momentum: 'Momentum',
  volatilite_relative: 'Volatilité relative',
  volume_relatif: 'Volume relatif',
  retour_moyenne: 'Retour à la moyenne',
  regle_candle_color: 'Couleur de bougie',
  regle_candle_streak: 'Série de bougies',
  regle_doji: 'Doji',
  regle_dragonfly_doji: 'Doji libellule',
  regle_gravestone_doji: 'Doji pierre tombale',
  regle_hammer: 'Marteau',
  regle_hanging_man: 'Pendu',
  regle_inverted_hammer: 'Marteau inversé',
  regle_shooting_star: 'Étoile filante',
  regle_marubozu: 'Marubozu',
  regle_spinning_top: 'Toupie',
  regle_engulfing: 'Avalement',
  regle_harami: 'Harami',
  regle_piercing_line: 'Ligne pénétrante',
  regle_dark_cloud_cover: 'Nuage noir',
  regle_tweezer: 'Pinces',
  regle_inside_bar: 'Barre intérieure',
  regle_outside_bar: 'Barre extérieure',
  regle_morning_star: 'Étoile du matin',
  regle_evening_star: 'Étoile du soir',
  regle_three_white_soldiers: 'Trois soldats blancs',
  regle_three_black_crows: 'Trois corbeaux noirs',
  regle_three_inside: 'Trois à l’intérieur',
  regle_three_outside: 'Trois à l’extérieur',
  regle_three_methods: 'Trois méthodes',
  regle_heikin_ashi: 'Heikin-Ashi',
  regle_session_open: 'Bougie d’ouverture',
  regle_session_move: 'Mouvement de séance',
  regle_opening_range_breakout: 'Cassure du range d’ouverture',
  regle_previous_day_range: 'Range de la veille',
  regle_pivot_point: 'Point pivot',
  regle_hour_of_day: 'Plage horaire',
  regle_day_of_week: 'Jour de la semaine',
  regle_day_of_month: 'Jour du mois',
  regle_momentum: 'Momentum en volatilité',
  regle_moving_average: 'Moyenne mobile',
  regle_moving_average_cross: 'Croisement de moyennes simples',
  regle_exponential_moving_average: 'Moyenne exponentielle',
  regle_exponential_moving_average_cross: 'Croisement de moyennes exponentielles',
  regle_macd: 'MACD',
  regle_linear_regression_slope: 'Pente de régression',
  regle_directional_movement: 'Mouvement directionnel',
  regle_adx: 'ADX',
  regle_vortex: 'Vortex',
  regle_aroon: 'Aroon',
  regle_cci: 'CCI',
  regle_ichimoku_cloud: 'Nuage d’Ichimoku',
  regle_supertrend: 'Supertrend',
  regle_parabolic_sar: 'SAR parabolique',
  regle_efficiency_ratio: 'Ratio d’efficacité',
  regle_autocorrelation: 'Autocorrélation',
  regle_market_structure: 'Structure de marché',
  regle_donchian_breakout: 'Cassure de Donchian',
  regle_fractal_breakout: 'Cassure de fractale',
  regle_narrow_range: 'Range étroit',
  regle_squeeze: 'Sortie de compression',
  regle_volatility_breakout: 'Cassure de volatilité',
  regle_rsi: 'RSI à seuils',
  regle_stochastic_rsi: 'RSI stochastique',
  regle_stochastic: 'Stochastique',
  regle_ultimate_oscillator: 'Ultimate Oscillator',
  regle_internal_bar_strength: 'Force interne de la barre',
  regle_bollinger_bands: 'Bandes de Bollinger',
  regle_keltner_channel: 'Canal de Keltner',
  regle_volume_surge: 'Pic de volume',
  regle_on_balance_volume: 'On-Balance Volume',
  regle_force_index: 'Force Index',
  regle_money_flow_index: 'Money Flow Index',
  regle_chaikin_money_flow: 'Chaikin Money Flow',
  regle_ease_of_movement: 'Ease of Movement',
  regle_balance_of_power: 'Balance of Power',
  regle_vwap: 'VWAP'
};

export const libelleModule = cle => NOMS_MODULES[cle] ?? cle;
